### ISSUE TITLE
User Accounts: Store and load exercise settings

### ISSUE THREAD

**Issue by Anish701** [AI-Coach-PT/ExerSights#36]
As already implemented, users can open a settings modal on each exercise page to adjust feedback settings, such as target knee angle, target hip angle, etc. These settings values should be stored on the Firestore cloud database and be linked to each user. The values should be pulled from the database and should be updated whenever the user makes an update to them.

**Comment by jilinzheng** [comment]
Will you be creating a Firebase project and giving permissions to me and James to collaborate on the same project?

**Comment by Anish701** [comment]
Yes. You should have access now.

**Comment by jilinzheng** [comment]
Also add an user greeting/user-specific info when logged in, on the app menubar

**Comment by jilinzheng** [comment]
load happens when page first loads, not modal; also whenever user hits save and close, i.e. storing
store happens when save and close is hit on modal
if load does not get any valid data, use default
