### ISSUE TITLE
Generalize visibility checking

### ISSUE THREAD

**Issue by jilinzheng** [AI-Coach-PT/ExerSights#63]
Allow devs to pass in a list/array of landmarks to be checked

**Comment by jilinzheng** [comment]
Extension of #34

**Comment by Anish701** [comment]
I can handle this as part of my refactoring

**Comment by Anish701** [comment]
I addressed this issue in https://github.com/AI-Coach-PT/ExerSights/commit/3fb10f3c982e8cdf4de419638a8b86408c67026f
This is part of my refactoring branch and will be pushed with the completion of the following refactoring issue: https://github.com/AI-Coach-PT/ExerSights/commit/3fb10f3c982e8cdf4de419638a8b86408c67026f
